"""修改了一些属性名

Revision ID: 65f776ede1bf
Revises: 7dfa1adf673c
Create Date: 2019-01-11 22:34:12.573278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f776ede1bf'
down_revision = '7dfa1adf673c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following'], ['user.id'], )
    )
    op.drop_table('fans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('guanzhu', sa.INTEGER(), nullable=True),
    sa.Column('fensi', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fensi'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guanzhu'], ['user.id'], )
    )
    op.drop_table('follow')
    # ### end Alembic commands ###
