"""修改粉丝关系

Revision ID: 7dfa1adf673c
Revises: 867b10bd9f65
Create Date: 2019-01-11 13:06:37.982522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfa1adf673c'
down_revision = '867b10bd9f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('guanzhu', sa.Integer(), nullable=True),
    sa.Column('fensi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fensi'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guanzhu'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fans')
    # ### end Alembic commands ###
